// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/update_state.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_update_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_update_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_update_state_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ServerStateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigUpdate  map[string]string      `protobuf:"bytes,1,rep,name=config_update,json=configUpdate,proto3" json:"config_update,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStateUpdate) Reset() {
	*x = ServerStateUpdate{}
	mi := &file_proto_update_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStateUpdate) ProtoMessage() {}

func (x *ServerStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_update_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStateUpdate.ProtoReflect.Descriptor instead.
func (*ServerStateUpdate) Descriptor() ([]byte, []int) {
	return file_proto_update_state_proto_rawDescGZIP(), []int{1}
}

func (x *ServerStateUpdate) GetConfigUpdate() map[string]string {
	if x != nil {
		return x.ConfigUpdate
	}
	return nil
}

var File_proto_update_state_proto protoreflect.FileDescriptor

const file_proto_update_state_proto_rawDesc = "" +
	"\n" +
	"\x18proto/update_state.proto\x12\fupdate_state\x1a\x1bgoogle/protobuf/empty.proto\"*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xac\x01\n" +
	"\x11ServerStateUpdate\x12V\n" +
	"\rconfig_update\x18\x01 \x03(\v21.update_state.ServerStateUpdate.ConfigUpdateEntryR\fconfigUpdate\x1a?\n" +
	"\x11ConfigUpdateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xaf\x01\n" +
	"\rUpdateService\x12J\n" +
	"\x0fBroadcastUpdate\x12\x1f.update_state.ServerStateUpdate\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x15SubscribeStateUpdates\x12\x16.google.protobuf.Empty\x1a\x1f.update_state.ServerStateUpdate0\x01B\n" +
	"Z\b./userpbb\x06proto3"

var (
	file_proto_update_state_proto_rawDescOnce sync.Once
	file_proto_update_state_proto_rawDescData []byte
)

func file_proto_update_state_proto_rawDescGZIP() []byte {
	file_proto_update_state_proto_rawDescOnce.Do(func() {
		file_proto_update_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_update_state_proto_rawDesc), len(file_proto_update_state_proto_rawDesc)))
	})
	return file_proto_update_state_proto_rawDescData
}

var file_proto_update_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_update_state_proto_goTypes = []any{
	(*User)(nil),              // 0: update_state.User
	(*ServerStateUpdate)(nil), // 1: update_state.ServerStateUpdate
	nil,                       // 2: update_state.ServerStateUpdate.ConfigUpdateEntry
	(*emptypb.Empty)(nil),     // 3: google.protobuf.Empty
}
var file_proto_update_state_proto_depIdxs = []int32{
	2, // 0: update_state.ServerStateUpdate.config_update:type_name -> update_state.ServerStateUpdate.ConfigUpdateEntry
	1, // 1: update_state.UpdateService.BroadcastUpdate:input_type -> update_state.ServerStateUpdate
	3, // 2: update_state.UpdateService.SubscribeStateUpdates:input_type -> google.protobuf.Empty
	3, // 3: update_state.UpdateService.BroadcastUpdate:output_type -> google.protobuf.Empty
	1, // 4: update_state.UpdateService.SubscribeStateUpdates:output_type -> update_state.ServerStateUpdate
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_update_state_proto_init() }
func file_proto_update_state_proto_init() {
	if File_proto_update_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_update_state_proto_rawDesc), len(file_proto_update_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_update_state_proto_goTypes,
		DependencyIndexes: file_proto_update_state_proto_depIdxs,
		MessageInfos:      file_proto_update_state_proto_msgTypes,
	}.Build()
	File_proto_update_state_proto = out.File
	file_proto_update_state_proto_goTypes = nil
	file_proto_update_state_proto_depIdxs = nil
}
