// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/network/proto/update_state.proto

package userpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HLC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WallTime      int64                  `protobuf:"varint,1,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	Logical       uint32                 `protobuf:"varint,2,opt,name=logical,proto3" json:"logical,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HLC) Reset() {
	*x = HLC{}
	mi := &file_internal_network_proto_update_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HLC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HLC) ProtoMessage() {}

func (x *HLC) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_proto_update_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HLC.ProtoReflect.Descriptor instead.
func (*HLC) Descriptor() ([]byte, []int) {
	return file_internal_network_proto_update_state_proto_rawDescGZIP(), []int{0}
}

func (x *HLC) GetWallTime() int64 {
	if x != nil {
		return x.WallTime
	}
	return 0
}

func (x *HLC) GetLogical() uint32 {
	if x != nil {
		return x.Logical
	}
	return 0
}

func (x *HLC) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type SettingEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Clock         *HLC                   `protobuf:"bytes,3,opt,name=clock,proto3" json:"clock,omitempty"`
	Deleted       bool                   `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"` // tombstone
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingEntry) Reset() {
	*x = SettingEntry{}
	mi := &file_internal_network_proto_update_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingEntry) ProtoMessage() {}

func (x *SettingEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_proto_update_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingEntry.ProtoReflect.Descriptor instead.
func (*SettingEntry) Descriptor() ([]byte, []int) {
	return file_internal_network_proto_update_state_proto_rawDescGZIP(), []int{1}
}

func (x *SettingEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SettingEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SettingEntry) GetClock() *HLC {
	if x != nil {
		return x.Clock
	}
	return nil
}

func (x *SettingEntry) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type ServerStateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *SettingEntry          `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerStateUpdate) Reset() {
	*x = ServerStateUpdate{}
	mi := &file_internal_network_proto_update_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStateUpdate) ProtoMessage() {}

func (x *ServerStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_proto_update_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStateUpdate.ProtoReflect.Descriptor instead.
func (*ServerStateUpdate) Descriptor() ([]byte, []int) {
	return file_internal_network_proto_update_state_proto_rawDescGZIP(), []int{2}
}

func (x *ServerStateUpdate) GetEntry() *SettingEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocalState    []*SettingEntry        `protobuf:"bytes,1,rep,name=local_state,json=localState,proto3" json:"local_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_internal_network_proto_update_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_proto_update_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_internal_network_proto_update_state_proto_rawDescGZIP(), []int{3}
}

func (x *SyncRequest) GetLocalState() []*SettingEntry {
	if x != nil {
		return x.LocalState
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewerEntries  []*SettingEntry        `protobuf:"bytes,1,rep,name=newer_entries,json=newerEntries,proto3" json:"newer_entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_internal_network_proto_update_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_network_proto_update_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_internal_network_proto_update_state_proto_rawDescGZIP(), []int{4}
}

func (x *SyncResponse) GetNewerEntries() []*SettingEntry {
	if x != nil {
		return x.NewerEntries
	}
	return nil
}

var File_internal_network_proto_update_state_proto protoreflect.FileDescriptor

const file_internal_network_proto_update_state_proto_rawDesc = "" +
	"\n" +
	")internal/network/proto/update_state.proto\x1a\x1bgoogle/protobuf/empty.proto\"U\n" +
	"\x03HLC\x12\x1b\n" +
	"\twall_time\x18\x01 \x01(\x03R\bwallTime\x12\x18\n" +
	"\alogical\x18\x02 \x01(\rR\alogical\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\"l\n" +
	"\fSettingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1a\n" +
	"\x05clock\x18\x03 \x01(\v2\x04.HLCR\x05clock\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted\"8\n" +
	"\x11ServerStateUpdate\x12#\n" +
	"\x05entry\x18\x01 \x01(\v2\r.SettingEntryR\x05entry\"=\n" +
	"\vSyncRequest\x12.\n" +
	"\vlocal_state\x18\x01 \x03(\v2\r.SettingEntryR\n" +
	"localState\"B\n" +
	"\fSyncResponse\x122\n" +
	"\rnewer_entries\x18\x01 \x03(\v2\r.SettingEntryR\fnewerEntries2{\n" +
	"\rUpdateService\x12E\n" +
	"\x15SubscribeStateUpdates\x12\x16.google.protobuf.Empty\x1a\x12.ServerStateUpdate0\x01\x12#\n" +
	"\x04Sync\x12\f.SyncRequest\x1a\r.SyncResponseB\n" +
	"Z\b./userpbb\x06proto3"

var (
	file_internal_network_proto_update_state_proto_rawDescOnce sync.Once
	file_internal_network_proto_update_state_proto_rawDescData []byte
)

func file_internal_network_proto_update_state_proto_rawDescGZIP() []byte {
	file_internal_network_proto_update_state_proto_rawDescOnce.Do(func() {
		file_internal_network_proto_update_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_network_proto_update_state_proto_rawDesc), len(file_internal_network_proto_update_state_proto_rawDesc)))
	})
	return file_internal_network_proto_update_state_proto_rawDescData
}

var file_internal_network_proto_update_state_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_network_proto_update_state_proto_goTypes = []any{
	(*HLC)(nil),               // 0: HLC
	(*SettingEntry)(nil),      // 1: SettingEntry
	(*ServerStateUpdate)(nil), // 2: ServerStateUpdate
	(*SyncRequest)(nil),       // 3: SyncRequest
	(*SyncResponse)(nil),      // 4: SyncResponse
	(*emptypb.Empty)(nil),     // 5: google.protobuf.Empty
}
var file_internal_network_proto_update_state_proto_depIdxs = []int32{
	0, // 0: SettingEntry.clock:type_name -> HLC
	1, // 1: ServerStateUpdate.entry:type_name -> SettingEntry
	1, // 2: SyncRequest.local_state:type_name -> SettingEntry
	1, // 3: SyncResponse.newer_entries:type_name -> SettingEntry
	5, // 4: UpdateService.SubscribeStateUpdates:input_type -> google.protobuf.Empty
	3, // 5: UpdateService.Sync:input_type -> SyncRequest
	2, // 6: UpdateService.SubscribeStateUpdates:output_type -> ServerStateUpdate
	4, // 7: UpdateService.Sync:output_type -> SyncResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_network_proto_update_state_proto_init() }
func file_internal_network_proto_update_state_proto_init() {
	if File_internal_network_proto_update_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_network_proto_update_state_proto_rawDesc), len(file_internal_network_proto_update_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_network_proto_update_state_proto_goTypes,
		DependencyIndexes: file_internal_network_proto_update_state_proto_depIdxs,
		MessageInfos:      file_internal_network_proto_update_state_proto_msgTypes,
	}.Build()
	File_internal_network_proto_update_state_proto = out.File
	file_internal_network_proto_update_state_proto_goTypes = nil
	file_internal_network_proto_update_state_proto_depIdxs = nil
}
